on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: pip3 install -r requirements.txt && pytest